module.exports=[
  {
      id:101,
      imgUrl:'../../image/美容养颜.png',
      title:'美容养颜',
      type:0
  },{
      id:102,
      imgUrl:"../../image/医药保健.png",
      title:"保健",
      type:1
  },{
      id:103,
      imgUrl:"../../image/蜂蜜.png",
      title:"补养",
      type:2
  },{
      id:104,
      imgUrl:"../../image/减肥瘦身.png",
      title:"减肥",
      type:3
  },{
      id:105,
      imgUrl:"../../image/母婴.png",
      title:"母婴",
      type:4
  },{
      id:106,
      imgUrl:"../../image/叶子.png",
      title:"气节",
      type:5
  },{
      id:107,
      imgUrl:"../../image/餐饮.png",
      title:"餐饮",
      type:6
  },{
      id:108,
      imgUrl:"../../image/药瓶.png",
      title:"维生素",
      type:7
  }
]